services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.local
    volumes:
      - ./secure_clipboard.sqlite:/app/secure_clipboard.sqlite
    restart: unless-stopped