services:
  app:
    build: .
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
    env_file:
      - .env.local
    volumes:
      - ./secure_clipboard.sqlite:/app/secure_clipboard.sqlite
      - ./.env.local:/app/.env.local
    restart: unless-stopped