services:
  app:
    build: .
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - DB_DATA_DIR=/app/data
    env_file:
      - .env.local
    volumes:
      - vaulty-data:/app/data
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped

volumes:
  vaulty-data:
    name: vaulty-data
    external: true